"""empty message

Revision ID: 38fd14e98cf3
Revises: 3a1bb112b08
Create Date: 2014-08-24 13:05:07.039459

"""

# revision identifiers, used by Alembic.
revision = '38fd14e98cf3'
down_revision = '3a1bb112b08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
