"""empty message

Revision ID: 3a1bb112b08
Revises: 334fcef9cb28
Create Date: 2014-08-24 13:03:42.565138

"""

# revision identifiers, used by Alembic.
revision = '3a1bb112b08'
down_revision = '334fcef9cb28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
