"""empty message

Revision ID: 20a059184243
Revises: 35ebdc8b5620
Create Date: 2014-08-11 19:58:51.647262

"""

# revision identifiers, used by Alembic.
revision = '20a059184243'
down_revision = '35ebdc8b5620'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
