"""empty message

Revision ID: 511fa822bba9
Revises: None
Create Date: 2014-08-07 22:36:56.910471

"""

# revision identifiers, used by Alembic.
revision = '511fa822bba9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'author')
    ### end Alembic commands ###
