application: ideashare-ver0
version: 1
runtime: php
api_version: 1

handlers:
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: \1
  upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /dist/dist/css
  static_dir: dist/dist/css

- url: /dist/dist/fonts
  static_dir: dist/dist/fonts

- url: /dist/dist/js
  static_dir: dist/dist/js

- url: /(.*\.(php|html))
  script: \1

- url: /.*
  script: index.html